### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ghost** [organization/MineJS#25]
Hi there.. I seem to be getting these issue on startup. Could you help.

OS: Win10

```
E:\MinecraftJS\sources\raknet\server\SessionManager.js:9
        this.registerPackets();
             ^

TypeError: this.registerPackets is not a function
    at new SessionManager (E:\MinecraftJS\sources\raknet\server\SessionManager.js:9:14)
    at new UDPServerSocket (E:\MinecraftJS\sources\raknet\server\UDPServerSocket.js:8:31)
    at Function.getInstance (E:\MinecraftJS\sources\raknet\server\UDPServerSocket.js:18:13)
    at process.<anonymous> (E:\MinecraftJS\sources\Server.js:791:62)
    at emitTwo (events.js:130:20)
    at process.emit (events.js:213:7)
    at handleMessage (internal/child_process.js:753:14)
    at Pipe.channel.onread (internal/child_process.js:472:11)
E:\MinecraftJS\sources\raknet\server\SessionManager.js:9
        this.registerPackets();
             ^

TypeError: this.registerPackets is not a function
    at new SessionManager (E:\MinecraftJS\sources\raknet\server\SessionManager.js:9:14)
    at new UDPServerSocket (E:\MinecraftJS\sources\raknet\server\UDPServerSocket.js:8:31)
    at Function.getInstance (E:\MinecraftJS\sources\raknet\server\UDPServerSocket.js:18:13)
    at process.<anonymous> (E:\MinecraftJS\sources\Server.js:791:62)
    at emitTwo (events.js:130:20)
    at process.emit (events.js:213:7)
    at handleMessage (internal/child_process.js:753:14)
    at Pipe.channel.onread (internal/child_process.js:472:11)
E:\MinecraftJS\sources\Server.js:685
                minejs.Server.getServer().getWorker(balancedWorkerIndex).send([minejs.network.ProcessProtocol.UDP, msg, rinfo.address, rinfo.port]);
                                                                        ^

TypeError: Cannot read property 'send' of undefined
    at Socket.udpSocket.on (E:\MinecraftJS\sources\Server.js:685:73)
    at emitTwo (events.js:125:13)
    at Socket.emit (events.js:213:7)
    at UDP.onMessage [as onmessage] (dgram.js:619:8)
```

**Comment by ghost** [comment]
@JellyBrick

**Comment by ghost** [comment]
@onebone @BetaF1sh @Happysttim @HelloWorld017 @Nesffer
